### ISSUE TITLE
Reviews

### ISSUE THREAD

**Issue by rudeboybert** [rudeboybert/forestecology#80]
- [x] Bert ~investigates~ does 1 in #84 
- [x] Dave does 2 in #81 
- [x] ~Dave~ Bert does 3 in #84
- [x] Bert does 4 in #82 

(1) In Allen & Kim (2020) we demonstrate how the package can be used to test whether taxonomic or trait-based groupings better explain competition. With clever application the package can be used in many different ways, even within the current structure of the model presented in Allen & Kim (2020).

> So, the package already has an example in Allen and Kim.  Perhaps you need to revisit this application or better yet, implement the suggestion embedded in the current MS: Thus an extension of the model would allow λ values from Equation 1 to be a function of the traits of competing species.

(2) The reviewer is correct that our model takes as an input the competitive distance. But it would be easier to iteratively run our model for a range of competitive distances, compute the RMSE estimate of out-of-sample model error for each distance, then perform basic model selection by opting for the model with the lowest RMSE value.

> This seems a really straightforward example to code up.  Even if it's just two distances and a comparison.  Please do this.

(3) In Allen & Kim (2020) we show how our current structure can be used to test whether trait-based groups better explain competition than taxonomic groupings (e.g., species). So again with clever application of our package different theories of competition can be tested.

> Is there an easy additional example of 'clever application' you can nudge readers along to understand?  I'd like to see one implemented.
> 
> Ultimately, we would appreciate you making an effort to showcase the package with respect to how it allows fundamental questions to be addressed and hypotheses generated.  Judicious use of GitHub/Zenodo based code and appendices can make for an efficient expansion of the examples.

(4) The sf simple features package is a relatively new package whose features allowed us to code our spatial cross-validation algorithm in an comprehensible and legible fashion. This would’ve been much harder to achieve using previously popular R packages for geospatial data, such as the sp package. This package would make neighborhood competition models accessible to a larger group of ecologists.

> I am not sure you've got this detail in the work.  It's certainly worth having it in and perhaps even associating the explanation more strongly with the structure and type of information that can be leveraged for all the 'clever extensions' of the package.
